generatorName: php-laravel-lg
outputDir: samples/server/petstore/php/laravel/lg
inputSpec: modules/openapi-generator/src/test/resources/3_0/petstore.yaml
templateDir: modules/openapi-generator/src/main/resources/php-laravel-lg
additionalProperties:
  hideGenerationTimestamp: "true"
